In [22]:
from CoRe_Dataloader_Envelope_Cut import CoRe_DB_Dataset
import pathlib as p
import matplotlib.pyplot as plt
import numpy as np
import torch
ds = CoRe_DB_Dataset(cdb_path=p.Path(r'C:\Users\aashr\Desktop\research\testing_grounds\CoRe_DB'))

In [23]:
ds.ueoss,len(ds.ueoss),ds.ueosscounts,sum(ds.ueosscounts),len(ds.pspace),len(ds)

(array(['2B', '2H', 'ALF2', 'BHBlp', 'BLQ', 'BLh', 'DD2', 'ENG', 'G2',
        'G2k123', 'H4', 'LS220', 'MPA1', 'MS1', 'MS1b', 'SFHo', 'SLy',
        'SLy4', 'sly'], dtype='<U6'),
 19,
 array([ 24,  12, 215,  13,  20,  52,  29,  11,  52,  16, 293,  28,  21,
         39, 475,  30, 990,   9,  36], dtype=int64),
 2365,
 2365,
 2365)

In [24]:
mds = []
for c in range(len(ds)):
    st,md = ds[c]
    mds.append(md)
te = torch.vstack(mds)[:,0]

In [25]:
a,b = np.unique(te,return_counts=True)

In [26]:
import torch.nn.functional as F

In [30]:
x = torch.tensor(1/b)
x = x*100
F.sigmoid(x),F.tanh(x).to(torch.float32)

(tensor([0.9847, 0.9998, 0.6142, 0.9995, 0.9933, 0.8725, 0.9692, 0.9999, 0.8725,
         0.9981, 0.5845, 0.9727, 0.9915, 0.9285, 0.5524, 0.9656, 0.5252, 1.0000,
         0.9415], dtype=torch.float64),
 tensor([0.9995, 1.0000, 0.4342, 1.0000, 0.9999, 0.9582, 0.9980, 1.0000, 0.9582,
         1.0000, 0.3286, 0.9984, 0.9999, 0.9882, 0.2075, 0.9975, 0.1007, 1.0000,
         0.9923]))